<?php

namespace Spira\ZuoraSdk\DataObjects;

use Spira\ZuoraSdk\DataObject;

/**
 * @see https://knowledgecenter.zuora.com/BC_Developers/SOAP_API/E1_SOAP_API_Object_Reference/PaymentMethod
 */
class PaymentMethod extends DataObject
{
    protected $type = 'PaymentMethod';

    public static function getDefaultColumns()
    {
        return [
            'AccountId',
            'Active',
            'AchAbaCode',
            'AchAccountName',
            // 'AchAccountNumber', // Insert-only field
            'AchAccountNumberMask',
            'AchAccountType',
            'AchAddress1',
            'AchAddress2',
            'AchBankName',
            'BankBranchCode',
            'BankCheckDigit',
            'BankCity',
            'BankCode',
            'BankIdentificationNumber',
            'BankName',
            'BankPostalCode',
            'BankStreetName',
            'BankStreetNumber',
            'BankTransferAccountName',
            // 'BankTransferAccountNumber',// Insert-only field
            'BankTransferAccountNumberMask',
            'BankTransferAccountType',
            'BankTransferType',
            'BusinessIdentificationCode',
            'City',
            'Country',
            'CreatedById',
            'CreatedDate',
            'CreditCardAddress1',
            'CreditCardAddress2',
            'CreditCardCity',
            'CreditCardCountry',
            'CreditCardExpirationMonth',
            'CreditCardExpirationYear',
            'CreditCardHolderName',
            'CreditCardMaskNumber',
            // 'CreditCardNumber', // Insert-only field
            'CreditCardPostalCode',
            // 'CreditCardSecurityCode', // To ensure PCI compliance, this value is not stored and cannot be queried.
            'CreditCardState',
            'CreditCardType',
            'DeviceSessionId',
            'Email',
            'FirstName',
            'IBAN',
            'Id',
            'IPAddress',
            'LastFailedSaleTransactionDate',
            'LastName',
            'LastTransactionDateTime',
            'LastTransactionStatus',
            'ExistingMandate',
            'MandateCreationDate',
            'MandateID',
            'MandateReceived',
            'MandateUpdateDate',
            'MaxConsecutivePaymentFailures',
            'Name',
            'NumConsecutiveFailures',
            'PaymentMethodStatus',
            'PaymentRetryWindow',
            'PaypalBaid',
            'PaypalEmail',
            'PaypalPreapprovalKey',
            'PaypalType',
            'Phone',
            'PostalCode',
            // 'SkipValidation', // Insert-only field
            'State',
            'StreetName',
            'StreetNumber',
            'TotalNumberOfErrorPayments',
            'TotalNumberOfProcessedPayments',
            'Type',
            'UpdatedById',
            'UpdatedDate',
            'UseDefaultRetryRule',
        ];
    }

    public static function getOptionalColumns()
    {
        return [
            'AccountId',
            'AchAbaCode',
            'AchAccountName',
            'AchAccountNumberMask',
            'AchAccountType',
            'AchAddress1',
            'AchAddress2',
            'AchBankName',
            'BankBranchCode',
            'BankCheckDigit',
            'BankCity',
            'BankCode',
            'BankIdentificationNumber',
            'BankName',
            'BankPostalCode',
            'BankStreetName',
            'BankStreetNumber',
            'BankTransferAccountName',
            'BankTransferAccountNumberMask',
            'BankTransferAccountType',
            'BankTransferType',
            'BusinessIdentificationCode',
            'City',
            'Country',
            'CreditCardAddress1',
            'CreditCardAddress2',
            'CreditCardCity',
            'CreditCardCountry',
            'CreditCardExpirationMonth',
            'CreditCardExpirationYear',
            'CreditCardHolderName',
            'CreditCardMaskNumber',
            'CreditCardPostalCode',
            'CreditCardState',
            'CreditCardType',
            'DeviceSessionId',
            'Email',
            'FirstName',
            'IBAN',
            'IPAddress',
            'LastFailedSaleTransactionDate',
            'LastTransactionDateTime',
            'LastTransactionStatus',
            'LastName',
            'ExistingMandate',
            'MandateCreationDate',
            'MandateID',
            'MandateReceived',
            'MandateUpdateDate',
            'Name',
            'PaypalPreapprovalKey',
            'Phone',
            'PostalCode',
            'State',
            'StreetName',
            'StreetNumber',
            'MaxConsecutivePaymentFailures',
            'PaymentMethodStatus',
            'PaymentRetryWindow',
            'PaypalBaid',
            'PaypalEmail',
            'PaypalType',
        ];
    }
}
